version: '3.8'

services:
  threat-detector:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: python app/api/detector_api.py 